#ifndef UNITTYPE_H
#define UNITTYPE_H

enum UnitType { WORKER, SETTLER, WARRIOR, ARCHER, PIKEMAN, HORSEMAN, SCOUT, HORSE_ARCHER, CATAPULT,
                TREBUCHET, TRIREME, GALLEY, KNIGHT, CROSSBOWMAN, LANDSNACK, LONGSWORDSMAN, MUSKETMAN,
                RIFLEMAN, CARAVEL, CANNON, LANCER, CAVALRY, INFANTRY, FRIGATE, IRONCLAD, ARTILLERY, TANK,
                PARATROOPER, ANTI_TANK_GUN, AA, BATTLESHIP, DESTROYER, SUBMARINE, NUKE, MOBILE_SAM,
                MODERN_INFANTRY, MODERN_ARMOR, FIGHTER, BOMBER, GDR, GANDHI_DR
              };


#endif // UNITTYPE_H
