version: 'R-1612.{build}'

environment:
 matrix:
  - QT5: C:\Qt\5.5\mingw492_32
    MINGW: C:\Qt\Tools\mingw492_32
  - QT5: C:\Qt\5.6\mingw49_32
    MINGW: C:\Qt\Tools\mingw492_32
  - QT5: C:\Qt\5.7\mingw53_32
    MINGW: C:\Qt\Tools\mingw530_32
matrix:
 fast_finish: true
 
branches:
 only:
   - master
   
skip_non_tags: true
init:
  - git config --global core.autocrlf input
  
clone_folder: c:\projects\ProjectHiawatha\
platform: Any CPU
configuration: release

before_build:
 - set PATH=%MINGW%\bin;%QT5%\bin;%PATH%

build_script:
  - qmake -v
  - qmake -r
  - mingw32-make
